

file_path = r'c:\Users\DELL\Downloads\DocumentSearch_v5\DocumentSearch\src\ui\dashboard.py'

# Piece 1: Start to line 480 (approx)
# We'll take everything up to `summary = extract_summary(queue_stats)` in the current broken file.
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

piece_1 = lines[:480] 
# Ensure piece_1 ends exactly after `summary = extract_summary(queue_stats)`
# Actually, let's find the line.
for i, line in enumerate(piece_1):
    if 'summary = extract_summary(queue_stats)' in line and i > 470:
        piece_1 = lines[:i+1]
        break

# Piece 2: The missing logic from what we saw in Step 1338
# I will re-type it from the history.
piece_2 = [
    "\n",
    "            # Safely get nested values with defaults\n",
    "            def safe_get(d, *keys, default=0):\n",
    "                \"\"\"Safely traverse nested dict structure\"\"\"\n",
    "                try:\n",
    "                    result = d\n",
    "                    for key in keys:\n",
    "                        if result is None:\n",
    "                            return default\n",
    "                        result = result.get(key, default) if isinstance(result, dict) else default\n",
    "                    return result if result is not None else default\n",
    "                except Exception:\n",
    "                    return default\n",
    "            \n",
    "            # Calculate values with safe access\n",
    "            discovered = size_stats.get('discovered', {}) or {}\n",
    "            in_pipeline = size_stats.get('in_pipeline', {}) or {}\n",
    "            searchable = size_stats.get('searchable', {}) or {}\n",
    "            failed = size_stats.get('failed', {}) or {}\n",
    "            \n",
    "            # Total progress with safe int conversion\n",
    "            total_discovered = safe_get(discovered, 'files', default=0)\n",
    "            total_searchable_root = safe_get(searchable, 'files', default=0)\n",
    "            total_searchable_items = safe_get(searchable, 'items', default=0)\n",
    "            \n",
    "            # If items count is 0 (legacy), fallback to root count\n",
    "            if total_searchable_items == 0:\n",
    "                total_searchable_items = total_searchable_root\n",
    "                \n",
    "            total_embedded = max(0, total_searchable_items - total_searchable_root)\n",
    "            \n",
    "            total_in_pipeline = safe_get(in_pipeline, 'files', default=0)\n",
    "            total_failed = safe_get(failed, 'files', default=0)\n",
    "            \n",
    "            discovered_size = safe_get(discovered, 'size_bytes', default=0)\n",
    "            searchable_size = safe_get(searchable, 'size_bytes', default=0)\n",
    "            pipeline_size = safe_get(in_pipeline, 'size_bytes', default=0)\n",
    "            \n",
    "            if show_as_files:\n",
    "                progress_pct = (total_searchable_root / max(total_discovered, 1)) * 100\n",
    "            else:\n",
    "                progress_pct = (searchable_size / max(discovered_size, 1)) * 100\n",
    "            \n",
    "            st.markdown(\"---\")\n",
    "            \n",
    "            # Main progression display\n",
    "            if show_as_files:\n",
    "                # File count view\n",
    "                st.markdown(\"### 📂 Total Discovered\")\n",
    "                st.markdown(f\"**{total_discovered:,}** files\")\n",
    "                \n",
    "                st.markdown(\"### 🔄 In Pipeline\")\n",
    "                st.markdown(f\"**{total_in_pipeline:,}** files\")\n",
    "                \n",
    "                st.markdown(\"### 🔍 Searchable\")\n",
    "                st.markdown(f\"**{total_searchable_root:,}** root files\")\n",
    "                if total_embedded > 0:\n",
    "                    st.caption(f\"+ {total_embedded:,} embedded items\")\n",
    "                \n",
    "                if total_failed > 0:\n",
    "                    st.markdown(\"### ❌ Failed\")\n",
    "                    st.markdown(f\"**{total_failed:,}** files\")\n",
    "            else:\n",
    "                # Data size view\n",
    "                st.markdown(\"### 📂 Total Discovered\")\n",
    "                st.markdown(f\"**{format_size(discovered_size)}**\")\n",
    "                st.caption(f\"{total_discovered:,} files\")\n",
    "                \n",
    "                st.markdown(\"### 🔄 In Pipeline\")\n",
    "                st.markdown(f\"**{format_size(pipeline_size)}**\")\n",
    "                st.caption(f\"{total_in_pipeline:,} files processing\")\n",
    "                \n",
    "                st.markdown(\"### 🔍 Searchable\")\n",
    "                st.markdown(f\"**{format_size(searchable_size)}**\")\n",
    "                st.caption(f\"{total_searchable_root:,} files ({total_searchable_items:,} items)\")\n",
    "                \n",
    "                if total_failed > 0:\n",
    "                    st.markdown(\"### ❌ Failed\")\n",
    "                    st.caption(f\"{total_failed:,} files failed\")\n",
    "            \n",
    "            st.markdown(\"---\")\n",
    "            \n",
    "            # Overall progress bar\n",
    "            st.markdown(\"### Overall Progress\")\n",
    "            st.progress(min(progress_pct / 100, 1.0), text=f\"{progress_pct:.1f}% complete\")\n",
    "            \n",
    "            st.markdown(\"---\")\n",
    "            \n",
    "            # Pipeline status (compact)\n",
    "            st.markdown(\"### ⚙️ Pipeline\")\n",
    "            \n",
    "            # Discovery\n",
    "            discovery_total = summary.get('discovered_total', 0) or 0\n",
    "            discovery_completed = summary.get('discovery_completed', 0) or 0\n",
    "            discovery_pending = summary.get('discovery_pending', 0) or 0\n",
    "            if discovery_total > 0 or discovery_pending > 0:\n",
    "                discovery_pct = (discovery_completed / discovery_total * 100) if discovery_total > 0 else 0\n",
    "                st.progress(min(discovery_pct / 100, 1.0), text=f\"Discovery: {discovery_pct:.0f}% ({discovery_completed:,}/{discovery_total:,})\")\n",
    "            \n",
    "            # Extraction\n",
    "            extraction_total = summary.get('extraction_total', 0) or 0\n",
    "            extraction_completed = summary.get('extraction_completed', 0) or 0\n",
    "            extraction_pending = summary.get('extraction_pending', 0) or 0\n",
    "            extraction_processing = summary.get('extraction_processing', 0) or 0\n",
    "            if extraction_total > 0 or extraction_pending > 0 or extraction_processing > 0:\n",
    "                extraction_pct = (extraction_completed / extraction_total * 100) if extraction_total > 0 else 0\n",
    "                status_text = f\"Extraction: {extraction_pct:.0f}% ({extraction_completed:,}/{extraction_total:,})\"\n",
    "                if extraction_processing > 0:\n",
    "                    status_text += f\" | Processing: {extraction_processing:,}\"\n",
    "                st.progress(min(extraction_pct / 100, 1.0), text=status_text)\n",
    "            \n",
    "            # Indexing\n",
    "            indexing_total = summary.get('indexing_total', 0) or 0\n",
    "            indexing_completed = summary.get('indexing_completed', 0) or 0\n",
    "            indexing_pending = summary.get('indexing_pending', 0) or 0\n",
    "            indexing_processing = summary.get('indexing_processing', 0) or 0\n",
    "            if indexing_total > 0 or indexing_pending > 0 or indexing_processing > 0:\n",
    "                indexing_pct = (indexing_completed / indexing_total * 100) if indexing_total > 0 else 0\n",
    "                status_text = f\"Indexing: {indexing_pct:.0f}% ({indexing_completed:,}/{indexing_total:,})\"\n",
    "                if indexing_processing > 0:\n",
    "                    status_text += f\" | Processing: {indexing_processing:,}\"\n",
    "                st.progress(min(indexing_pct / 100, 1.0), text=status_text)\n",
    "            \n",
    "            # OCR\n",
    "            ocr_total = summary.get('ocr_total', 0) or 0\n",
    "            ocr_completed = summary.get('ocr_completed', 0) or 0\n",
    "            ocr_pending = summary.get('ocr_pending', 0) or 0\n",
    "            ocr_processing = summary.get('ocr_processing', 0) or 0\n",
    "            if ocr_total > 0 or ocr_pending > 0 or ocr_processing > 0:\n",
    "                ocr_pct = (ocr_completed / ocr_total * 100) if ocr_total > 0 else 0\n",
    "                status_text = f\"OCR: {ocr_pct:.0f}% ({ocr_completed:,}/{ocr_total:,})\"\n",
    "                if ocr_processing > 0:\n",
    "                    status_text += f\" | Processing: {ocr_processing:,}\"\n",
    "                st.progress(min(ocr_pct / 100, 1.0), text=status_text)\n",
    "            \n",
    "            if discovery_total == 0 and extraction_total == 0 and indexing_total == 0 and \\\n",
    "               discovery_pending == 0 and extraction_pending == 0 and indexing_pending == 0 and \\\n",
    "               (size_stats or queue_stats):\n",
    "                st.info(\"System ready. No active processing.\")\n",
    "        \n",
    "        except Exception as e:\n",
    "            error_msg = str(e)\n",
    "            if \"no such table\" in error_msg.lower() or \"no such column\" in error_msg.lower():\n",
    "                # Database was reset - reset the singleton and try to re-create a fresh instance\n",
    "                reset_queue_manager()\n",
    "                queue_manager = get_queue_manager()\n",
    "                try:\n",
    "                    size_stats = queue_manager.get_size_statistics() or {}\n",
    "                    queue_stats = queue_manager.get_queue_statistics() or {}\n",
    "                    summary = extract_summary(queue_stats)\n",
    "                except Exception:\n",
    "                    # Still not available - show empty metrics and notify user\n",
    "                    st.markdown(\"---\")\n",
    "                    st.markdown(\"### 📂 Total Discovered\")\n",
    "                    st.markdown(\"**0** files\")\n",
    "                    st.markdown(\"### 🔄 In Pipeline\")\n",
    "                    st.markdown(\"**0** files\")\n",
    "                    st.markdown(\"### 🔍 Searchable\")\n",
    "                    st.markdown(\"**0** files\")\n",
    "                    st.progress(0.0, text=\"0% complete\")\n",
    "                    st.info(\"🔄 System reset. Start the orchestrator to begin processing.\")\n",
    "            else:\n",
    "                # Show fallback UI with error message\n",
    "                st.markdown(\"---\")\n",
    "                st.markdown(\"### 📂 Total Discovered\")\n",
    "                st.markdown(\"**-** files\")\n",
    "                st.markdown(\"### 🔄 In Pipeline\")\n",
    "                st.markdown(\"**-** files\")\n",
    "                st.markdown(\"### 🔍 Searchable\")\n",
    "                st.markdown(\"**-** files\")\n",
    "                st.progress(0.0, text=\"Unable to load stats\")\n",
    "                st.warning(f\"Stats unavailable: {str(e)[:100]}\")\n",
    "\n",
    "\n",
    "def render_search_tab(config: Any, os_client: Optional[OpenSearchClient]) -> None:\n",
    "    \"\"\"Render the search interface tab.\"\"\"\n",
    "    st.markdown(\"### Search Your Documents\")\n",
    "    \n",
    "    # Search input\n",
    "    col1, col2 = st.columns([5, 1])\n",
    "    with col1:\n",
    "        query = st.text_input(\n",
    "            \"Search documents\", \n",
    "            placeholder=\"Enter keywords, filenames, or exact phrases in quotes...\", \n",
    "            label_visibility=\"collapsed\",\n",
    "            key=\"search_input\"\n",
    "        )\n",
    "    with col2:\n",
    "        search_button = st.button(\"🔍 Search\", use_container_width=True)\n",
    "    \n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    if not os_client:\n",
    "        st.error(\"OpenSearch is not available. Please check the system status.\")\n",
    "        return\n",
    "    \n",
    "    # Perform search\n",
    "    if (query and len(query) >= 2) or search_button:\n",
    "        if query and len(query) >= 2:\n",
    "            with st.spinner(\"Searching...\"):\n",
    "                try:\n",
    "                    results = perform_search(os_client, query)\n",
    "                    if results:\n",
    "                        render_search_results(results, query)\n",
    "                    else:\n",
    "                        st.info(\"💤 No documents indexed yet. Start the orchestrator to begin indexing.\")\n",
    "                        st.caption(\"Once documents are indexed, you'll be able to search through them here.\")\n",
    "                except Exception as e:\n",
    "                    st.error(f\"Search error: {e}\")\n",
    "        else:\n",
    "            st.warning(\"Please enter at least 2 characters to search.\")\n",
    "    else:\n",
    "        # Show recent documents\n",
    "        render_recent_documents(os_client)\n",
    "\n",
    "\n",
    "def extract_snippet_manually(text: str, query: str, max_length: int = 180) -> str:\n",
    "    \"\"\"Extract snippet around query match when highlights unavailable.\"\"\"\n",
    "    if not text:\n",
    "        return \"\"\n",
    "    \n",
    "    # Normalize for searching\n",
    "    text_lower = text.lower()\n",
    "    query_lower = query.lower()\n",
    "    query_terms = query_lower.split()\n",
    "    \n",
    "    # Find first occurrence of any query term\n",
    "    best_pos = -1\n",
    "    best_term = \"\"\n",
    "    for term in query_terms:\n",
    "        pos = text_lower.find(term)\n",
    "        if pos != -1 and (best_pos == -1 or pos < best_pos):\n",
    "            best_pos = pos\n",
    "            best_term = term\n",
    "    \n",
    "    if best_pos == -1:\n",
    "        # No match found, return beginning\n",
    "        return text[:max_length] + \"...\" if len(text) > max_length else text\n",
    "    \n",
    "    # Extract context around match\n",
    "    start = max(0, best_pos - max_length // 2)\n",
    "    end = min(len(text), start + max_length)\n",
    "    snippet = text[start:end]\n",
    "    \n",
    "    # Add ellipsis\n",
    "    if start > 0:\n",
    "        snippet = \"...\" + snippet\n",
    "    if end < len(text):\n",
    "        snippet = snippet + \"...\"\n",
    "    \n",
    "    # Highlight matching terms\n",
    "    import re\n",
    "    for term in query_terms:\n",
    "        if len(term) >= 3:  # Only highlight meaningful terms\n",
    "            pattern = re.compile(re.escape(term), re.IGNORECASE)\n",
    "            snippet = pattern.sub(lambda m: f\"**{m.group()}**\", snippet)\n",
    "    \n",
    "    return snippet\n",
    "\n",
    "\n",
    "def _generate_ocr_variants(query: str) -> List[str]:\n",
    "    \"\"\"\n",
    "    Generate query variants to handle common OCR character misrecognition.\n",
    "    \n",
    "    Common OCR errors:\n",
    "    - 0 (zero) ↔ O (letter O)\n",
    "    - 1 (one) ↔ l (lowercase L) ↔ I (uppercase i)\n",
    "    - 5 ↔ S\n",
    "    - 8 ↔ B\n",
    "    - rn ↔ m\n",
    "    - cl ↔ d\n",
    "    - vv ↔ w\n",
    "    \"\"\"\n",
    "    if not query:\n",
    "        return [query]\n",
    "    \n",
    "    variants = set([query])\n"
]

# Piece 3: From `query_lower = query.lower()` to the end
# We'll find where `query_lower = query.lower()` starts in the current broken file.
piece_3 = []
found_p3 = False
for line in lines:
    if 'query_lower = query.lower()' in line and not found_p3:
        # Check if it's the one at line 481
        found_p3 = True
        piece_3.append(line)
        continue
    if found_p3:
        piece_3.append(line)

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(piece_1)
    f.writelines(piece_2)
    f.writelines(piece_3)

print("Reconstruction complete.")
