import zipfile
import shutil
import logging
from pathlib import Path
import os

# Setup logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("debug_extraction")

# Mock file path (use one generated by stress test)
FILE_PATH = r"C:\Users\DELL\Downloads\TestDocuments\stress_doc_0.docx"
FILE_HASH = "debug_hash_123"
EMBEDDED_ROOT = Path("data/embedded_debug")

def extract_embedded_images(file_path: str, file_hash: str):
    logger.info(f"Testing extraction for {file_path}")
    
    if not os.path.exists(file_path):
        logger.error("File does not exist!")
        return
        
    if not zipfile.is_zipfile(file_path):
        logger.error("Not a zip file")
        return

    IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp', '.svg'}
    extracted_count = 0
    
    try:
        embedded_dir = EMBEDDED_ROOT / file_hash
        embedded_dir.mkdir(parents=True, exist_ok=True)
        
        with zipfile.ZipFile(file_path, 'r') as zf:
            print("Zip Content:")
            for name in zf.namelist():
                print(f" - {name}")
                if name.endswith('/'): continue
                
                suffix = Path(name).suffix.lower()
                if suffix in IMAGE_EXTENSIONS:
                    print("   -> MATCH! Extracting...")
                    safe_name = name.replace('/', '_').replace('\\', '_')
                    target_path = embedded_dir / safe_name
                    
                    with zf.open(name) as source, open(target_path, 'wb') as target:
                        shutil.copyfileobj(source, target)
                    
                    extracted_count += 1
        
        logger.info(f"Extracted {extracted_count} images.")
        
    except Exception as e:
        logger.error(f"Error: {e}")

if __name__ == "__main__":
    extract_embedded_images(FILE_PATH, FILE_HASH)
